
#HTML todo: show usefull html stuff with browser

# JSON
### unknown verb (json)
PATCH http://localhost/catwork/post
Accept: application/json

### unknown controller (json)
PATCH http://localhost/catwork/adsdg
Accept: application/json


### Get all posts
GET http://localhost/catwork/post
Accept: application/json

### Get specific post
GET http://localhost/catwork/post
Accept: application/json

### SignUp (should fail)
POST http://localhost/catwork/signup
Accept: application/json
Content-Type: application/json

{ "username": "admin", "password" : "doesn't matter"}





### Get User Details
GET http://localhost/catwork/user/admin
Accept: application/json
Content-Type: application/json


### Get all users (only id and username, to improve frontend)
GET http://localhost/catwork/user
Accept: application/json
Content-Type: application/json



### Login (user_id = 1)
POST http://localhost/catwork/login
Accept: application/json
Content-Type: application/json

{ "user": "admin",
  "password": "password"}


### Post new Image (requires login)
POST http://localhost/catwork/post
Accept: application/json
Content-Type: application/json

{
  "author_id" : 1,
  "title" :  "test",
  "description" : null,
  "image" : "",
  "timestamp" : null
}


### Like Image (requires login)
POST http://localhost/catwork/like/1
Accept: application/json
Content-Type: application/json

### Remove Like Image (requires login)
DELETE http://localhost/catwork/like/1
Accept: application/json
Content-Type: application/json


### Logout
GET http://localhost/catwork/logout
