<?php include __DIR__."/_header.phtml"; ?>
<?php /** @var Domains_Base $data */ ?>
    <?php if ($data) { ?>
<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Key</th>
        <th>Value</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($data->property_names() as $property_name) {
        ?>
        <tr>
            <td><?=$property_name?></td>
            <?php
             if ($property_name == "image" && $data->$property_name != null) {
                 ?>
                    <td>
                        <img width="50px" height="50px" style="object-fit: cover;" src="<?=$data->$property_name?>"/>
                    </td>
                    <?php
                }
                else {
                ?>
                <td><?=$data->$property_name?></td>
                <?php
                }
                ?>
        </tr>
        <?php
    }
    ?>
    </tbody>
</table>
    <?php } else { ?>
        <div>No data found.</div>
    <?php } ?>
<?php include __DIR__."/_footer.phtml"; ?>