<?php include __DIR__."/../_header.phtml"; ?>
<?php /** @var Domains_FreezerItem $data */ ?>
    <?php if ($data) { ?>
<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Entry</th>
        <th>Description</th>
        <th>Expiration Date</th>
        <th>Details</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($data as $obj) {
        ?>
        <tr>
            <td><?=$obj->id?></td>
            <td><?=$obj->name?></td>
            <td><?=$obj->entry?></td>
            <td><?=$obj->description?></td>
            <td><?=$obj->exp?></td>
            <td><a href="./FreezerItem/<?=($obj->id)?>" class="link-primary">Details</a></td>
            <td><button onclick="delete_freezer(<?=($obj->id)?>)" class="btn btn-danger">Delete</button></td>
        </tr>
        <?php
    }
    ?>
    </tbody>
</table>
    <?php } ?>

<h2>Add new</h2>
<form method="POST" action="">
    <div class="form-group">
        <label>Name</label>
        <input type="text" name="name" class="form-control">
    </div>
    <div class="form-group">
        <label>Entry</label>
        <input type="date" name="entry" class="form-control">
    </div>
    <div class="form-group">
        <label>Description</label>
        <input type="text" name="description" class="form-control">
    </div>
    <div class="form-group">
        <label>Expiration Date</label>
        <input type="date" name="exp" class="form-control">
    </div>
    <br>
    <input type="submit" class="btn btn-primary">
</form>

<script>
    function delete_freezer(id){
        fetch('./FreezerItem/' + id, { method: 'DELETE' })
            .then(() => location.reload());
    }
</script>
<?php include __DIR__."/../_footer.phtml"; ?>